// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package firebase

import (
	"firebase-playground/internal/interface/handler"
)

// Injectors from wire.go:

//go:generate wire
func InitializeFirebaseRouter() IRouter {
	iFirebaseHandler := handler.NewFirebaseHandler()
	iRouter := NewRouter(iFirebaseHandler)
	return iRouter
}
