// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"firebase-playground/internal/application/usecase"
	"firebase-playground/internal/infrastructure/firebase"
	"firebase-playground/internal/interface/handler"
	"firebase-playground/internal/interface/middleware"
)

// Injectors from wire.go:

//go:generate wire
func InitializeUserRouter() IRouter {
	iUserHandler := handler.NewUserHandler()
	iAuthenticateUsecase := usecase.NewAuthenticateUsecase()
	iAuthenticateHandler := handler.NewAuthenticateHandler(iAuthenticateUsecase)
	iRouter := NewRouter(iUserHandler, iAuthenticateHandler)
	return iRouter
}

//go:generate wire
func InitializeFirebaseGoogleAuthClient() (*middleware.FirebaseGoogleMiddleware, error) {
	client, err := firebase.NewFirebaseAuthClient()
	if err != nil {
		return nil, err
	}
	firebaseGoogleMiddleware := middleware.NewFirebaseGoogleMiddleware(client)
	return firebaseGoogleMiddleware, nil
}
